CREATE DATABASE IF NOT EXISTS holamundo;
USE holamundo;

CREATE TABLE IF NOT EXISTS visitas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO visitas (fecha) VALUES (NOW());